### ISSUE TITLE
Perform exploratory testing

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#208] opened 2022-04-21 04:54 UTC
**Acceptance criteria**:
- take the tour over the main functionality
- take the tour where you deliberately perform the weirdest actions
- take one more tour, whichever you see fit

**Artifacts**
- the tour reports in the form of comments under this issue

**Comment by khaledismaeel** [comment] 2022-04-29 00:42
# Tour 1

**Subject**: main functionality check
**Tester**: Khaled Ismaeel, `@khaledismaeel`
**Duration**: ~30 mins

|Step|Action|Outcome|Result|Comments|
|----|------|-------|------|--------|
|1|Press on the Plan B podcast card|I get redirected to URL `https://cast-iu.pages.dev/podcasts/3` which contains a list of episode cards |OK|Perhaps it would have been more user friendly if the URL contained some human-readable name rather than an ID|
|2|Press on the play button on the first episode|The audio controls are set to the first episode and the episode starts playing|OK||
|3|Press on the stop button on audio controls|The episode stops playing, though after considerable delay (around 3~4 seconds)|Suboptimal|Such a delay is not convenient, though the functionality is correct|
|4|Press the play button on audio controls|The episode starts playing, again, after 3~4 seconds delay|Suboptimal|Same as step 3|
|5|Press on the like button next to an episode (without prior login)|The like toggle is set and a snackbar asking me to login in order to synchronize my likes has appeared|OK||
|6|Press the sign in button that appeared on the snackbar in the previous step|A snackbar that says "successfully signed in" appeared|OK||
|7|Sign in from incognito mode and check the same podcast|Podcast loads with all like toggles unset|OK||
|8|Press the like button of a separate episode and sign in when the snackbar asks|The like toggle of the previously liked episode is set, but no the most recent one|NO|I would expect both episodes to be stored as liked|
|9|Open "Your Library"|One episode is shown in the library, the one which was liked previously|OK||
|10|Go back home and open the CaucasTalk podcast and press "Download" on some episode|A progress percentage is shown, then gets stuck at 60%, but continued after a page refresh. After it finished it said episode is available offline|OK||
|11|Go to "Your Library"|The previously downloaded episode is shown in the "Avilable offline" section|OK|Capitalization in "Your Library" and "Avilable offline" is inconsistent|
|12|Play the only episode in the avilable offline section|It plays!|OK||
|13|Disable internet connection and play the only episode in the available offline seciton|It plays!|OK||
|14|Enable the internet connection again and refresh the library page (accidentally discovered)|The available offline section is empty. Going back to the home page and opening the gallery again shows the one episode in the available offline section|NO|That refresh should not change anything in the page|

**Comment by khaledismaeel** [comment] 2022-04-29 02:13
**Subject**: weird beahvior check (antisocial tour)
**Tester**: Khaled Ismaeel, `@khaledismaeel`
**Duration**: ~25 minutes


|Step|Action|Outcome|Result|Comments|
|----|------|-------|------|--------|
|1|Open two tabs of the same application and log in from one only one|Both tabs signed in|OK||
|2|Sign out from one of the tabs|Both tabs signed out, but there was an episode in the recently listened in both tabs|NO|I would expect that signing out clears _all_ history|
|3|Clear cache in one of the tabs|Both tabs lost that episode from the recently played section|OK||
|4|Play an episode in one of the tabs|The episode plays in one of the tabs only|OK||
|5|Play two different episodes in the two tabs|Two different audios are played|OK||
|6|Like an episode in the one of the tabs|The other tab does not mark the episode as liked until after refresh|Mostly OK||
|7|Download the same episode in two tabs|The downloads progress at the same speed|OK||
|8|Refresh one of the tabs before the previous download completes|The progress is lost, although the download continues normally in the other tab|Confusing (not necessarily wrong)|The syncing behavior between two tabs on the same browser might be confusing to a user. Likes are shared among different tabs, but downloads and playbacks are not.|
|9|Download the same episode in two tabs and exit the page which started the download first before the download finishes|The other download continues normally|OK||
|10|Open a separate tab and navigate to the library|the available offline section is empty|NO|This is probably the same issue as the one encountered in the |

**Comment by khaledismaeel** [comment] 2022-04-29 02:38
# Tour 3

**Subject**: obsessive compulsive behavior
**Tester**: Khaled Ismaeel, `@khaledismaeel`
**Duration**: ~25 minutes

|Step|Action|Outcome|Result|Comments|
|----|------|-------|------|--------|
|1|Press the play toggle as fast as you can for around 10 seconds|The playback functionality remains normal|OK||
|2|Press the like toggle as fast as you can for around 10 seconds|Still functions correctly|OK||
|3|Press random download and refresh buttons|After downloading everything eventually, it downloads correctly|OK||
|4|Press the sign in button as fast as you can for around 10 seconds|GitHub asks for reauthorization, but after allowing it signs in correctly|OK||
|5|Press the go forward and backward buttons randomly and quickly around the beginning, middle, and end of an episode|Not all presses cause the playback to go forward backward; around one out of 5 presses actually cause it to change|NO|I also noticed that I totally forgot about the now playing widget until now since it is sorta hard to find.|
|6|Repeat the previous step while also randomly toggling the the playback speed button and transcript|Same as before, but since the transcript and the playback speed buttons didn't add any crash, this step is marked as OK|OK||
|7|Use the scrub bar to seek random places in the playback|It doesn't always work to seek to a undownload section of the episode, around 1 in 3 times. Also, playback stops whenever the scrub bar is used|NO|Not sure whether stopping the playback is by design or not, but it certainly work 3 out of 3 times|

**Comment by khaledismaeel** [comment] 2022-04-29 02:47
The following is a summary of these test tours:

1. If you were to wait for a while after pressing play/pause, the next toggle takes considerable time to take effect.
2. The episode which caused the like snackbar to be triggered is not saved after signing in.
3. Refreshing the library page causes the downloaded episodes to disappear, although visiting the library from the home page displays them correctly.
4. There is a minor inconsistency in the UI in capitalization.
5. Signing out does not clear the history (likes, downloads, etc).
6. Syncing between two tabs in the same browser is confusing.
7. Playback controls don't work well with obsessive compulsive usage.
8. The now playing widget is kinda difficult to find.

**Closed by khaledismaeel** 2022-04-29 02:47 UTC
